Repository ansible/team-devtools, pull requests merged in 2022-04, with the labels that each got.

#48 Create CODEOWNERS
  .github/CODEOWNERS
Labels: skip-changelog

#47 autolabeler: reduce accidental double labeling
  .github/release-drafter.yml
Labels: skip-changelog

#44 Fix mermaid graph text color
  README.md
Labels: bug

#49 Update README.md
  README.md
Labels: enhancement

#42 Document molecule ecosystem
  README.md
Labels: enhancement
