Repository ansible/team-devtools, pull requests merged in 2022-03, with the labels that each got.

#39 Update release notes after merge
  .github/workflows/ack.yml
Labels: bug

#40 Updated repository list
  config/devtools.yml
Labels: bug

#41 Document devtools project dependencies
  README.md
Labels: documentation, enhancement

#43 Update README.md
  README.md
Labels: enhancement
