Repository ansible/team-devtools, pull requests merged in 2023-05, with the labels that each got.

#113 Add a collection release workflow
  .github/workflows/release_collection.yml
Labels: enhancement

#114 Fix boolean for release
  .github/workflows/release_collection.yml
Labels: bug

#112 Allow the push workflow to be run manually
  .github/workflows/push.yml
Labels: skip-changelog

#117 Remove ansible.cfg when done
  .github/workflows/release_collection.yml
Labels: skip-changelog

#121 Document release process for python packages
  docs/guides/python/release.md
  docs/guides/python/release_draft.png
Labels: bug, documentation

#122 Common Push workflow added
  .github/workflows/push_network.yml
Labels: enhancement
