Repository ansible/team-devtools, pull requests merged in 2024-11, with the labels that each got.

#232 Start using uv instead of pip during testing
  .github/workflows/tox.yml
  README.md
  docs/guides/calver-transition.md
  docs/guides/calver.md
  tox.ini
Labels: enhancement

#240 Improve messaging when number of coverage files collected was unexpected
  .github/workflows/tox.yml
Labels: bug

#241 Add support for py313
  .github/workflows/tox.yml
Labels: enhancement

#242 Move permissions to top level of reusable workflow
  .github/workflows/tox.yml
Labels: skip-changelog

#245 Revert "Bump codecov/codecov-action from 4.5.0 to 5.0.2"
  .github/workflows/tox.yml
Labels: bug

#250 Update releases.md
  docs/guides/releases.md
Labels: documentation

#251 Revert "Bump codecov/codecov-action from 4.5.0 to 5.0.2"
  .github/workflows/tox.yml
Labels: skip-changelog
