Repository ansible/team-devtools, pull requests merged in 2024-01, with the labels that each got.

#163 Include coverage stats for our projects
  .readthedocs.yml
  docs/guides/code-reviews.md
  tox.ini
Labels: bug

#164 Add calver transition document
  docs/guides/calver-transition.md
Labels: documentation, patch

#166 Add the start of a calver overview document
  docs/guides/calver.md
  mkdocs.yml
Labels: bug

#165 Document Python dependencies management
  .gitignore
  docs/guides/python/dependencies.md
  mkdocs.yml
Labels: documentation, enhancement
