Repository ansible/team-devtools, pull requests merged in 2024-12, with the labels that each got.

#254 Add Node.js setup support
  .github/workflows/test.yml
  .github/workflows/tox.yml
  .tool-versions
Labels: enhancement

#256 Update prettier
  .pre-commit-config.yaml
Labels: skip-changelog

#259 Fix docs urls
  docs/guides/releases.md
Labels: skip-changelog

#260 Update Dec release manager
  docs/guides/releases.md
Labels: skip-changelog

#246 Ensure we test coverage uploading
  .config/requirements-docs.in
  .config/requirements-test.in
  .config/requirements.in
  .github/workflows/test.yml
  .gitignore
  .readthedocs.yml
  codecov.yml
  pyproject.toml
  readthedocs.yml
  requirements.in
  src/team_devtools/__init__.py
  test/__init__.py
  test/test_one.py
  tox.ini
Labels: bug

#261 Allow passing skip_explode to dynamic-matrix
  .github/workflows/tox.yml
Labels: bug

#264 Allow installation of mise from tox workflow
  .github/workflows/test.yml
  .github/workflows/tox.yml
  .readthedocs.yml
  .tool-versions
Labels: bug

#266 Update release doc for Dec
  docs/guides/releases.md
Labels: skip-changelog
