Repository ansible/team-devtools, pull requests merged in 2024-10, with the labels that each got.

#221 Allow tox workflow to write packages
  .github/workflows/tox.yml
Labels: bug

#224 Add optional run_pre and run_post commands to tox workflow
  .github/workflows/test.yml
  .github/workflows/tox.yml
Labels: bug

#225 Revert "Add optional run_pre and run_post commands to tox workflow"
  .github/workflows/test.yml
  .github/workflows/tox.yml
Labels: bug

#222 Pin codecov action to v4.5.0 and update dependabot.yml to ignore v4.6.0
  .ansible-lint
  .github/dependabot.yml
  .github/workflows/tox.yml
Labels: bug

#226 Add optional run_pre and run_post commands to tox workflow
  .github/workflows/test.yml
  .github/workflows/tox.yml
Labels: bug

#227 Add release manager for the month of October
  docs/guides/releases.md
Labels: skip-changelog

#230 Use coactions/dynamic-matrix@v4 action
  .github/workflows/tox.yml
Labels: skip-changelog

#233 Ensure test pipeline runs on pull requests and pushes to main
  .github/workflows/push.yml
  .github/workflows/test.yml
Labels: skip-changelog

#235 Fix self test on push
  .github/workflows/test.yml
Labels: bug, skip-changelog

#236 Add repository status page
  .prettierignore
  docs/stats/repos.md
  mkdocs.yml
Labels: bug

#237 Fix push workflow call from test one
  .github/workflows/test.yml
Labels: bug

#238 Allow tox workflow to receive an optional environment argument
  .github/workflows/tox.yml
Labels: bug
