Repository ansible/team-devtools, pull requests merged in 2025-04, with the labels that each got.

#285 Update the release doc with devspaces upgrade information
  docs/guides/releases.md
Labels: enhancement

#284 Update releases.md for April
  docs/guides/releases.md
Labels: documentation, skip-changelog

#289 Update releases.md for April
  .config/dictionary.txt
  docs/guides/releases.md
Labels: documentation, skip-changelog

#288 Report test results with junit.xml if available.
  .github/workflows/test.yml
  .github/workflows/tox.yml
  .gitignore
  tox.ini
Labels: patch
