Repository ansible/team-devtools, pull requests merged in 2025-09, with the labels that each got.

#326 chore: add konflux and renovate bots to auto-approval
  .github/workflows/ack.yml
Labels: chore

#327 fix: require labels matching conventional commit prefixes
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .pre-commit-config.yaml
  config/devtools.yml
Labels: fix

#335 chore: more auto approval and auto-merge for bots
  .github/workflows/ack.yml
Labels: chore

#336 fix: use ansible/actions/matrix
  .github/workflows/tox.yml
Labels: fix

#337 fix: auto-label fix commits
  .github/release-drafter.yml
  pyproject.toml
Labels: fix

#339 fix: forum_post.py posting issue
  .github/workflows/forum_post.py
Labels: fix

#342 fix: forum_post.py post date
  .github/workflows/forum_post.py
Labels: fix

#344 fix: use macos-15 runner
  .github/workflows/test.yml
Labels: fix

#347 fix: prevent collection of venvs from inside .tox logs
  .github/workflows/tox.yml
Labels: fix

#348 chore: tox config sync
  .github/workflows/tox.yml
  .gitignore
  .pre-commit-config.yaml
  pyproject.toml
  test/test_one.py
  test/test_two.py
  uv.lock
Labels: chore, ignore-for-release

#351 fix: enable scheduled run
  .github/workflows/test.yml
  docs/stats/repos.md
Labels: fix

#343 Add project tag to forum posts
  .github/workflows/forum_post.py
  test/test_forum_post.py
Labels: feat

#353 fix: replace toml-sort with tombi
  .pre-commit-config.yaml
  .taplo.toml
  .vscode/extensions.json
  .vscode/settings.json
  AGENTS.md
  pyproject.toml
Labels: fix

#359 fix: refactor sonarcloud reporting
  .github/workflows/tox.yml
  sonar-project.properties
Labels: fix
